### ISSUE TITLE
Add VillageX to Portfolio

### ISSUE THREAD

**Issue by cbracco** [BigRoomStudios/bigroomstudios.com#16]
Images have already been created, I am waiting on text content (from @sefrankel I believe). Once received I will add this project to the portfolio!

**Comment by sefrankel** [comment]
Hey Chris, that text content is in the Google Document where we had posted some of the other portfolio blurbs during our big content push last week. It's been posted in the Slack channel a couple times, let me know if you need any revisions.

**Comment by cbracco** [comment]
Ah, sorry about that. Slipped through the cracks. I will add this one in today, then!

**Comment by cbracco** [comment]
This should be on staging & live now.

http://staging.bigroomstudios.com/work/village-x/
http://bigroomstudios.com/work/village-x/
