### ISSUE TITLE
The portfolio projects should provide links to the actual work

### ISSUE THREAD

**Issue by sefrankel** [BigRoomStudios/bigroomstudios.com#29]
When I view a portfolio page, a lot of it is (well done!) boilerplate, and my instinct is "yeah yeah, let me go and see the product." Links to the sites?

**Comment by cbracco** [comment]
Yeah, I can definitely add a button to the single work page template that links to the project. Should be simple!

**Comment by cbracco** [comment]
@sefrankel added "View Project >" buttons at the bottom of the description text for each project! :rocket: 

[Example](http://bigroomstudios.com/work/atlantic-fund-services/)
