### ISSUE TITLE
Arrow keys not working correctly on Chrome

### ISSUE THREAD

**Issue by cbracco** [BigRoomStudios/bigroomstudios.com#37]
Via @mattboutet  - Oddball OSX chrome bug - once you're out of the slide stack at the top of the homepage, the down arrow works as expected, but holding down the up arrow dumps you back into the slide deck, usually directly to the 2nd to last slide(?).  More of a curiosity than a real bug.

**Comment by mattboutet** [comment]
A quick test shows that this bug is fairly universal - I get the same behavior in FF and Chrome on Windows.

**Comment by cbracco** [comment]
Thanks @mattboutet! I think the jQuery plugin we are using hi-jacks arrow keys .. might be able to simply disable this with a setting: https://github.com/devinivy/pagePiling.js/blob/master/jquery.pagepiling.js#L46

**Comment by cbracco** [comment]
Yep, that seemed to be the problem. Fix should be up on staging & live now.
