### ISSUE TITLE
Social media links for Sam Frankel

### ISSUE THREAD

**Issue by sefrankel** [BigRoomStudios/bigroomstudios.com#44]
https://instagram.com/sefrankel/
https://twitter.com/Sefrankel
https://www.linkedin.com/in/sefrankel

**Comment by cbracco** [comment]
Haha, you are the best. Thanks for using github!

**Comment by cbracco** [comment]
Got this in there for ya on staging! Will likely be doing a push to live sometime early this week. http://staging.bigroomstudios.com/about/#about-team
