### ISSUE TITLE
404 on links from labs.bigroomstudios.com

### ISSUE THREAD

**Issue by rpvnwnkl** [BigRoomStudios/bigroomstudios.com#46]
I was surfing earlier today and noticed that clicking any link on the page leads to a 404: 

> __404 Not Found__
> nginx/1.6.2

I am not sure if that site is in this repo or is hosted somewhere else.

Here is the site: http://labs.bigroomstudios.com.

Just wanted to give a heads up.

**Comment by devinivy** [comment]
Thanks for the headsup!

CC @tmateosian

**Comment by devinivy** [comment]
@rpvnwnkl should be fixed– thanks again.
