### ISSUE TITLE
HOTFIX: Zack McCartney's pet in pet mode is incorrect

### ISSUE THREAD

**Issue by zemccartney** [BigRoomStudios/bigroomstudios.com#47]
My current pet is Simba, Zack's Lion

I EXPECTED / WANT WITHOUT PREVIOUSLY EXPRESSING TO ANYONE my pet to be Captain Scrumples, the Thompson's Point Groundhog that Zack has seen a few times outside the office. You mess with Scrump, you get dumped (those words exactly, fuck your <br> tags and orphans)

Here are some generic images.  I have not captured the good captain on film yet, but rest assured, I've seen him at least twice. HE EXISTS. 

![doggroundhog-small](https://cloud.githubusercontent.com/assets/7771785/9861040/efec8f9a-5afd-11e5-9783-a831745bb677.jpg)

![groundhog-day](https://cloud.githubusercontent.com/assets/7771785/9861042/f27f7286-5afd-11e5-8c6f-9d9fda034784.jpg)

TODO: 
- learn photoshop
- add Deal With It glasses to picture

**Comment by rbkh** [comment]
@zemccartney consider it done.

**Comment by cbracco** [comment]
@zemccartney @rbkh everything about this is wonderful

**Comment by devinivy** [comment]
CN WE LaUNCH YET???
